export type AlphabetCard = {
  char: string
  romaji: string
  meaning?: string
  tip?: string
  audio?: string
}

export type AlphabetSet = {
  id: string
  label: string
  cards: AlphabetCard[]
}

export const ALPHABET_DATA: Record<string, AlphabetSet[]> = {
  japanese: [
    {
      id: 'hiragana',
      label: 'Hiragana',
      cards: [
        { char: '\u3042', romaji: 'a', tip: 'Like "ah" — open vowel' },
        { char: '\u3044', romaji: 'i', tip: 'Like "ee" in "feet"' },
        { char: '\u3046', romaji: 'u', tip: 'Like "oo" but shorter' },
        { char: '\u3048', romaji: 'e', tip: 'Like "e" in "bed"' },
        { char: '\u304a', romaji: 'o', tip: 'Like "o" in "go"' },
        { char: '\u304b', romaji: 'ka', tip: 'K + a sound' },
        { char: '\u304d', romaji: 'ki', tip: 'K + i sound' },
        { char: '\u304f', romaji: 'ku', tip: 'K + u sound' },
        { char: '\u3051', romaji: 'ke', tip: 'K + e sound' },
        { char: '\u3053', romaji: 'ko', tip: 'K + o sound' },
        { char: '\u3055', romaji: 'sa', tip: 'S + a sound' },
        { char: '\u3057', romaji: 'shi', tip: 'Like "she"' },
        { char: '\u3059', romaji: 'su', tip: 'S + u sound' },
        { char: '\u305b', romaji: 'se', tip: 'S + e sound' },
        { char: '\u305d', romaji: 'so', tip: 'S + o sound' },
        { char: '\u305f', romaji: 'ta', tip: 'T + a sound' },
        { char: '\u3061', romaji: 'chi', tip: 'Like "chee"' },
        { char: '\u3064', romaji: 'tsu', tip: 'Like "ts" in "cats" + u' },
        { char: '\u3066', romaji: 'te', tip: 'T + e sound' },
        { char: '\u3068', romaji: 'to', tip: 'T + o sound' },
        { char: '\u306a', romaji: 'na', tip: 'N + a sound' },
        { char: '\u306b', romaji: 'ni', tip: 'N + i sound' },
        { char: '\u306c', romaji: 'nu', tip: 'N + u sound' },
        { char: '\u306d', romaji: 'ne', tip: 'N + e sound' },
        { char: '\u306e', romaji: 'no', tip: 'N + o sound' },
        { char: '\u306f', romaji: 'ha', tip: 'H + a sound' },
        { char: '\u3072', romaji: 'hi', tip: 'H + i sound' },
        { char: '\u3075', romaji: 'fu', tip: 'Soft "f" + u' },
        { char: '\u3078', romaji: 'he', tip: 'H + e sound' },
        { char: '\u307b', romaji: 'ho', tip: 'H + o sound' },
        { char: '\u307e', romaji: 'ma', tip: 'M + a sound' },
        { char: '\u307f', romaji: 'mi', tip: 'M + i sound' },
        { char: '\u3080', romaji: 'mu', tip: 'M + u sound' },
        { char: '\u3081', romaji: 'me', tip: 'M + e sound' },
        { char: '\u3082', romaji: 'mo', tip: 'M + o sound' },
        { char: '\u3084', romaji: 'ya', tip: 'Y + a sound' },
        { char: '\u3086', romaji: 'yu', tip: 'Y + u sound' },
        { char: '\u3088', romaji: 'yo', tip: 'Y + o sound' },
        { char: '\u3089', romaji: 'ra', tip: 'Soft R, between R and L' },
        { char: '\u308a', romaji: 'ri', tip: 'Soft R + i' },
        { char: '\u308b', romaji: 'ru', tip: 'Soft R + u' },
        { char: '\u308c', romaji: 're', tip: 'Soft R + e' },
        { char: '\u308d', romaji: 'ro', tip: 'Soft R + o' },
        { char: '\u308f', romaji: 'wa', tip: 'W + a sound' },
        { char: '\u3092', romaji: 'wo', tip: 'Used as object marker, sounds like "o"' },
        { char: '\u3093', romaji: 'n', tip: 'A standalone nasal sound — hold it for a beat' },
      ]
    },
    {
      id: 'katakana',
      label: 'Katakana',
      cards: [
        { char: '\u30A2', romaji: 'a', tip: 'Same sound as hiragana \u3042' },
        { char: '\u30A4', romaji: 'i', tip: 'Same sound as hiragana \u3044' },
        { char: '\u30A6', romaji: 'u', tip: 'Same sound as hiragana \u3046' },
        { char: '\u30A8', romaji: 'e', tip: 'Same sound as hiragana \u3048' },
        { char: '\u30AA', romaji: 'o', tip: 'Same sound as hiragana \u304a' },
        { char: '\u30AB', romaji: 'ka', tip: 'Used for foreign words — ka sound' },
        { char: '\u30AD', romaji: 'ki', tip: 'ki sound' },
        { char: '\u30AF', romaji: 'ku', tip: 'ku sound' },
        { char: '\u30B1', romaji: 'ke', tip: 'ke sound' },
        { char: '\u30B3', romaji: 'ko', tip: 'ko sound' },
        { char: '\u30B5', romaji: 'sa', tip: 'sa sound' },
        { char: '\u30B7', romaji: 'shi', tip: 'shi sound' },
        { char: '\u30B9', romaji: 'su', tip: 'su sound' },
        { char: '\u30BB', romaji: 'se', tip: 'se sound' },
        { char: '\u30BD', romaji: 'so', tip: 'so sound' },
        { char: '\u30BF', romaji: 'ta', tip: 'ta sound' },
        { char: '\u30C1', romaji: 'chi', tip: 'chi sound' },
        { char: '\u30C4', romaji: 'tsu', tip: 'tsu sound' },
        { char: '\u30C6', romaji: 'te', tip: 'te sound' },
        { char: '\u30C8', romaji: 'to', tip: 'to sound' },
        { char: '\u30CA', romaji: 'na', tip: 'na sound' },
        { char: '\u30CB', romaji: 'ni', tip: 'ni sound' },
        { char: '\u30CC', romaji: 'nu', tip: 'nu sound' },
        { char: '\u30CD', romaji: 'ne', tip: 'ne sound' },
        { char: '\u30CE', romaji: 'no', tip: 'no sound' },
        { char: '\u30CF', romaji: 'ha', tip: 'ha sound' },
        { char: '\u30D2', romaji: 'hi', tip: 'hi sound' },
        { char: '\u30D5', romaji: 'fu', tip: 'fu sound' },
        { char: '\u30D8', romaji: 'he', tip: 'he sound' },
        { char: '\u30DB', romaji: 'ho', tip: 'ho sound' },
        { char: '\u30DE', romaji: 'ma', tip: 'ma sound' },
        { char: '\u30DF', romaji: 'mi', tip: 'mi sound' },
        { char: '\u30E0', romaji: 'mu', tip: 'mu sound' },
        { char: '\u30E1', romaji: 'me', tip: 'me sound' },
        { char: '\u30E2', romaji: 'mo', tip: 'mo sound' },
        { char: '\u30E4', romaji: 'ya', tip: 'ya sound' },
        { char: '\u30E6', romaji: 'yu', tip: 'yu sound' },
        { char: '\u30E8', romaji: 'yo', tip: 'yo sound' },
        { char: '\u30E9', romaji: 'ra', tip: 'ra sound — soft R' },
        { char: '\u30EA', romaji: 'ri', tip: 'ri sound' },
        { char: '\u30EB', romaji: 'ru', tip: 'ru sound' },
        { char: '\u30EC', romaji: 're', tip: 're sound' },
        { char: '\u30ED', romaji: 'ro', tip: 'ro sound' },
        { char: '\u30EF', romaji: 'wa', tip: 'wa sound' },
        { char: '\u30F2', romaji: 'wo', tip: 'wo sound' },
        { char: '\u30F3', romaji: 'n', tip: 'n sound — standalone nasal' },
      ]
    }
  ],

  korean: [
    {
      id: 'consonants',
      label: 'Consonants',
      cards: [
        { char: '\u3131', romaji: 'g/k', tip: 'Like "g" at start, "k" at end of syllable' },
        { char: '\u3134', romaji: 'n', tip: 'Like "n" in "no"' },
        { char: '\u3137', romaji: 'd/t', tip: 'Like "d" at start, "t" at end' },
        { char: '\u3139', romaji: 'r/l', tip: 'Between R and L — rolled R sound' },
        { char: '\u3141', romaji: 'm', tip: 'Like "m" in "mom"' },
        { char: '\u3142', romaji: 'b/p', tip: 'Like "b" at start, "p" at end' },
        { char: '\u3145', romaji: 's', tip: 'Like "s" in "sun"' },
        { char: '\u3147', romaji: 'ng (silent)', tip: 'Silent when first, "ng" sound at end' },
        { char: '\u3148', romaji: 'j', tip: 'Like "j" in "joy"' },
        { char: '\u314a', romaji: 'ch', tip: 'Like "ch" in "church"' },
        { char: '\u314b', romaji: 'k', tip: 'Aspirated K — stronger puff of air' },
        { char: '\u314c', romaji: 't', tip: 'Aspirated T — stronger puff of air' },
        { char: '\u314d', romaji: 'p', tip: 'Aspirated P — stronger puff of air' },
        { char: '\u314e', romaji: 'h', tip: 'Like "h" in "hello"' },
      ]
    },
    {
      id: 'vowels',
      label: 'Vowels',
      cards: [
        { char: '\u3161', romaji: 'eu', tip: 'Unrounded — like the "u" in "put" without lip rounding' },
        { char: '\u3163', romaji: 'i', tip: 'Like "ee" in "feet"' },
        { char: '\u3160', romaji: 'yu', tip: 'Like "you"' },
        { char: '\u315c', romaji: 'u', tip: 'Like "oo" in "boot"' },
        { char: '\u3155', romaji: 'yeo', tip: 'Like "yuh"' },
        { char: '\u3153', romaji: 'eo', tip: 'Like "uh"' },
        { char: '\u315b', romaji: 'yo', tip: 'Like "yo" in "yoga"' },
        { char: '\u3157', romaji: 'o', tip: 'Like "o" in "go"' },
        { char: '\u3150', romaji: 'ae', tip: 'Like "a" in "cat"' },
        { char: '\u314f', romaji: 'a', tip: 'Like "a" in "father"' },
        { char: '\u3151', romaji: 'e', tip: 'Like "e" in "bed"' },
        { char: '\u3154', romaji: 'ye', tip: 'Like "ye" in "yes"' },
        { char: '\u3156', romaji: 'ya', tip: 'Like "ya" in "yard"' },
        { char: '\u3159', romaji: 'wa', tip: 'Like "wa" in "water"' },
        { char: '\u315a', romaji: 'wae', tip: 'Like "we" in "web"' },
        { char: '\u315e', romaji: 'we', tip: 'Like "we"' },
        { char: '\u315f', romaji: 'wi', tip: 'Like "wee"' },
        { char: '\u315d', romaji: 'wo', tip: 'Like "wo" in "won"' },
        { char: '\u3162', romaji: 'ui', tip: 'Like "eui" — tricky combo sound' },
        { char: '\u3158', romaji: 'wa', tip: 'Same sound as \u3159 — different vowel combo' },
      ]
    }
  ],

  chinese: [
    {
      id: 'hsk1',
      label: 'HSK 1 Characters',
      cards: [
        { char: '\u4e00', romaji: 'y\u012b', meaning: 'one', tip: 'The simplest character — one horizontal stroke' },
        { char: '\u4e8c', romaji: '\u00e8r', meaning: 'two', tip: 'Two horizontal strokes' },
        { char: '\u4e09', romaji: 's\u0101n', meaning: 'three', tip: 'Three horizontal strokes' },
        { char: '\u56db', romaji: 's\u00ec', meaning: 'four', tip: 'Four — looks like a box with legs' },
        { char: '\u4e94', romaji: 'w\u016f', meaning: 'five', tip: 'Five — cross-like shape' },
        { char: '\u516d', romaji: 'li\u00f9', meaning: 'six', tip: 'Six — like a person with arms out' },
        { char: '\u4e03', romaji: 'q\u012b', meaning: 'seven', tip: 'Seven — looks like a cross' },
        { char: '\u516b', romaji: 'b\u0101', meaning: 'eight', tip: 'Eight — two strokes spreading out' },
        { char: '\u4e5d', romaji: 'ji\u01d4', meaning: 'nine', tip: 'Nine — curved hook shape' },
        { char: '\u5341', romaji: 'sh\u00ed', meaning: 'ten', tip: 'Ten — a cross shape' },
        { char: '\u4eba', romaji: 'r\u00e9n', meaning: 'person', tip: 'Looks like a person walking' },
        { char: '\u597d', romaji: 'h\u01ceo', meaning: 'good', tip: 'Woman + child = good' },
        { char: '\u4e2d', romaji: 'zh\u014dng', meaning: 'middle/China', tip: 'A line through the middle of a box' },
        { char: '\u5927', romaji: 'd\u00e0', meaning: 'big', tip: 'A person with arms stretched wide' },
        { char: '\u5c0f', romaji: 'xi\u01ceo', meaning: 'small', tip: 'Small — three small dots' },
        { char: '\u5929', romaji: 'ti\u0101n', meaning: 'sky/day', tip: 'Big + a line on top = sky above' },
        { char: '\u6c34', romaji: 'shu\u01d0', meaning: 'water', tip: 'Looks like flowing water' },
        { char: '\u706b', romaji: 'hu\u01d2', meaning: 'fire', tip: 'Looks like flames rising' },
        { char: '\u6728', romaji: 'm\u00f9', meaning: 'tree/wood', tip: 'A tree with roots and branches' },
        { char: '\u91d1', romaji: 'j\u012bn', meaning: 'gold/money', tip: 'One of the five elements' },
        { char: '\u571f', romaji: 't\u01d4', meaning: 'earth/soil', tip: 'Earth — cross with base' },
        { char: '\u6708', romaji: 'yu\u00e8', meaning: 'moon/month', tip: 'Looks like a crescent moon' },
        { char: '\u65e5', romaji: 'r\u00ec', meaning: 'sun/day', tip: 'Looks like the sun — a circle with a line' },
        { char: '\u5c71', romaji: 'sh\u0101n', meaning: 'mountain', tip: 'Three peaks of a mountain' },
        { char: '\u53e3', romaji: 'k\u01d2u', meaning: 'mouth', tip: 'A square — like an open mouth' },
        { char: '\u773c', romaji: 'y\u01cen', meaning: 'eye', tip: 'Looks like an eye on its side' },
        { char: '\u8033', romaji: '\u011br', meaning: 'ear', tip: 'Resembles the shape of an ear' },
        { char: '\u624b', romaji: 'sh\u01d2u', meaning: 'hand', tip: 'Looks like an outstretched hand' },
        { char: '\u8db3', romaji: 'z\u00fa', meaning: 'foot', tip: 'Foot/leg character' },
        { char: '\u5fc3', romaji: 'x\u012bn', meaning: 'heart', tip: 'Resembles a heart shape' },
      ]
    }
  ]
}
